#+TITLE: Dot Files

- use =./install.sh= to install. This will create many symlinks in $HOME
- The newsrc.eld file is moved to history-files repo to keep this repo
  cleaner, and ~newsrc.eld~ is symlinked to
  =~/git/history-files=. Thus, I need to clone the repo.
- =setup-git.sh= setup the git user name and email, as well as
  storing the credentials

* GDM

=/etc/gdm/Xsession= reads the Xresources and Xmodmap.

=/etc/gdm/Xsession= actually reads the $HOME/.profile, thus in order
to use Guix emacs mode, you need a $HOME/.profile with:

#+BEGIN_EXAMPLE
source "$HOME/.guix-profile/etc/profile"
source "$HOME/.config/guix/current/etc/profile"
#+END_EXAMPLE

Or just load:

#+BEGIN_EXAMPLE
source $HOME/.bash_profile
#+END_EXAMPLE


* Quicklisp

To install quicklisp reliably, use

#+BEGIN_EXAMPLE
curl -O https://beta.quicklisp.org/quicklisp.lisp
sbcl --load quicklisp.lisp
(quicklisp-quickstart:install)
(ql:add-to-init-file)
#+END_EXAMPLE



* Tmp

Use S2716DG
#+BEGIN_EXAMPLE
xrandr --output DP-2 --rotate left --left-of DP-0
#+END_EXAMPLE

* ArchLinux + Guix

This is probably the best setup for now. GuixSD suffers from Nvidia
driver support, which is quite critical for me, because I need cuda
for my research. Other reasons including Kicad, pavucontrol.

I'm setting up Arch with minimum packages:

#+BEGIN_EXAMPLE
xfce4
gnome
gdm
nvidia
pkg-config
base-devel
build-essentials
xorg-xrandr
updatedb
xorg-xcursors
xorg-xclock
kicad
kicad-library
pavucontrol pulseaudio alsa-utils pulseaudio-alsa
ttf-dejavu
chromium
firefox
#+END_EXAMPLE

I also installed =git= and =emacs= during setup of course, but I need
to remove them, as the credential files are giving me troubles after
installing Guix ones.


The rest is to install Guix package manager as indicated on Guix
website, and install the packages in [[file:guix/package.scm][my manifest file]].
