set nocompatible


" vundle
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#begin()
Plugin 'tpope/vim-fugitive'
Plugin 'digitaltoad/vim-jade'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'Townk/vim-autoclose'
" <leader>c<space>: toggle
" <leader>cs: sexy comment: use /* ... */
Plugin 'scrooloose/nerdcommenter'
call vundle#end()
filetype plugin indent on
syntax on

"disable vim-markdown folding
let g:vim_markdown_folding_disabled=1

set nu

" number of spaces for any tab
set tabstop=2
" indent spaces
set shiftwidth=2
" insert space whenever tab key is pressed
set expandtab

" jump to last position when reopen a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g'\"" | endif
endif

" set map leader
let mapleader = ","

" highlight all matches
set hlsearch

set noswapfile
