#!/bin/sh

# unset SESSION_MANAGER
# unset DBUS_SESSION_BUS_ADDRESS
# OS=`uname -s`
# if [ $OS = 'Linux' ]; then
#   case "$WINDOWMANAGER" in
#     *gnome*)
#       if [ -e /etc/SuSE-release ]; then
#         PATH=$PATH:/opt/gnome/bin
#         export PATH
#       fi
#       ;;
#   esac
# fi
# if [ -x /etc/X11/xinit/xinitrc ]; then
#   exec /etc/X11/xinit/xinitrc
# fi
# if [ -f /etc/X11/xinit/xinitrc ]; then
#   exec sh /etc/X11/xinit/xinitrc
# fi
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# xsetroot -solid grey
# xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
# twm &

vncconfig -nowin &
# vncconfig -iconic &

# openbox-session &
# xmonad &
# dbus-launch gnome-session &
# gnome-session&
# startxfce4&
# stumpwm&

# FIXME exec? &?

# FIXME gnome-session cannot start
# exec gnome-session

# But xfce4 works, so I'm using this instead
exec startxfce4
# exec openbox-session
