xmodmap -e "pointer = 1 2 3 5 4"
xmodmap -e "keycode 66 = Control_L"
xmodmap -e "clear Lock"
xmodmap -e "add Control = Control_L"
xrdb ~/.Xresources
xcompmgr -c &

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

fcitx&
xscreensaver &

exec awesome
