#!/bin/bash


##############################
## .xinitrc file
##############################


# Load ~/.Xresources
# To see current loaded resources
# xrdb -query -all

# NEVER put xrdb into background,
# otherwise programs launched after xrdb may look for resouces before they are loaded

if [ -e ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi


# dynamically adjust DPI setting
dpi=$(xdpyinfo | grep resolution | awk '{print $2}')
# dpi="96x96"
dpi=${dpi%x*}
if [ -n $dpi ]; then
    dpi="$dpi*2"
    # dpi=$((dpi)) # not working, need to use bc
    dpi=$(echo $dpi | bc)
    echo "Xft.dpi: $dpi" | xrdb -merge
fi

# merge PRIMARY and CLIPBOARD xsel
if [ `which autocutsel` ]; then
    autocutsel &
    autocutsel -s PRIMARY &
fi    


##############################
## Virtual Box Setting
##############################

# start clipboard sharing

if [ `which VBoxClient` ]; then
    VBoxClient --clipboard
fi


##############################
## Applications
##############################

emacs --daemon &

if [ -e ~/.fehbg ]; then
   sh ~/.fehbg &
fi

xmodmap ~/.Xmodmap

##############################
## Window Manager
##############################

exec stumpwm
# exec openbox
# exec ratpoison
